#!/bin/sh
command -v update-desktop-database >/dev/null 2>&1 && update-desktop-database /usr/share/applications || true
command -v gtk-update-icon-cache >/dev/null 2>&1 && gtk-update-icon-cache -f -t /usr/share/icons/hicolor || true
command -v udevadm >/dev/null 2>&1 && udevadm control --reload-rules || true
exit 0
